# Generated by Django 4.2.1 on 2023-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='hpcsa_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='id_number',
            field=models.CharField(default=' ', max_length=13),
            preserve_default=False,
        ),
    ]
